# Default values for modernpets.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: <REGISTRY>/<NAMESPACE> # Ex: us.icr.io/mynamespace
  pullPolicy: Always
  pullSecret: ""

namespace: ""

ingress:
  enabled: false
  hosts:
    - jpetstore-web.app # Ex: jpetstore.myclustername.us-south.containers.appdomain.cloud 

isLB: true

httpHost: petstore-web.app
